### ISSUE TITLE
$var inside quotes

### ISSUE THREAD

**Issue by idleberg** [SublimeText/NSIS#19]
The current language definition does not highlight variables/definitions within any kind of quotes, this should probably be changed.

**Comment by idleberg** [comment]
Closed in 7b876042cf57589838ef53b465dfe7625dd89a2c

**Comment by portablesoft** [comment]
It is broken again. Please check and fix it. Thanks.

**Comment by idleberg** [comment]
Please double-check that this is not caused by your colour schemes. It works fine in themes that support string interpolation. If you're using one of Sublime Text's default colour schemes, Sixteen is the only one supporting that!

**Comment by portablesoft** [comment]
@idleberg Thanks for your reply. It's indeed the color scheme issue. I try the Sixteen scheme and it works well now.
