### ISSUE TITLE
Discuss: Tagged releases, new syntax file-format

### ISSUE THREAD

**Issue by idleberg** [SublimeText/NSIS#31]
CC @jeffory @FichteFoll 

Is there any opposition to tagging releases? I would like to convert the current TextMate file to the [new format](https://www.sublimetext.com/docs/3/syntax.html) for for syntax definitions and thought that versioning illustrate this cut nicely.

The conversion itself can be done using `convert_syntax.py` inside the Default package in (build 3103 and later).

**Proposal**:

* 1.0.0 for TextMate XML (`.tmLanguage`)
* 2.0.0 for Sublime Text YAML (`.sublime-syntax`)

Any arguments against this?

**Comment by FichteFoll** [comment]
I haven't had the time to review pull requests to the PC channel, but you should take a look at tag prefixes: https://github.com/wbond/package_control/blob/5643f4fa9a335a4591482a8ecdf6e0d7413fbaa1/example-repository.json#L260-L288

**Comment by idleberg** [comment]
Now using tag prefixes, waiting for the PC channel to merge changes 😉
