### ISSUE TITLE
Highlighting color changed with 2.0 release

### ISSUE THREAD

**Issue by robotroll** [SublimeText/NSIS#36]
Hi,

the colors of the keywords changed with the new version. I expected the update to also highlight the variables in strings, but with the same color as before:

Old:
![image](https://cloud.githubusercontent.com/assets/3962624/19431849/63a34e92-945a-11e6-9559-f8c44e8080a8.png)

New:
![image](https://cloud.githubusercontent.com/assets/3962624/19431854/6a581326-945a-11e6-91a4-9452c9ff4acc.png)

I use the Afterglow theme in standard configuration. There was no change to the theme.
Sublime version: Dev Channel, Build 3125

**Comment by idleberg** [comment]
Yes, as mentioned in the changelog, the scope names have been changed to be closer to the [TextMate Naming Conventions](https://manual.macromates.com/en/language_grammars).

**Comment by robotroll** [comment]
Fair enough. I'll find another theme.

Good catch with the missing $PROGRAMFILES32 variables.

**Comment by idleberg** [comment]
Let me add that there will be a couple of more refinements in the near future. Also, I'm planning to release a new base16 template for Sublime Text, Atom, CodeMirror, highlight.js themes with NSIS development in mind.
